language: node_js
node_js:
  - "6"
branches:
  only:
    - master
script:
  - git config user.email "shen.yichuan@gmail.com"
  - git config user.name "yishn"
  - npm start && git commit -a -m "Update" && git push origin master:gh-pages -f
notifications:
  email:
    on_success: never
    on_failure: change
